### ISSUE TITLE
KML is an XML language -- having trouble parsing the XML as it appears to expect JSON...

### ISSUE THREAD

**Issue by ddd1600** [ldonnet/rgeo-kml#1]
```
    2.2.1 :011 > geom = RGeo::Kml.decode(xml)
    NoMethodError: undefined method `[]' for #<REXML::Parsers::PullParser:0x007fed06823110>
        from /Users/daviddouglas/.rvm/gems/ruby-2.2.1/bundler/gems/rgeo-kml-e31a5c2bd56f/lib/rgeo/kml/coder.rb:242:in `decode'
        from /Users/daviddouglas/.rvm/gems/ruby-2.2.1/bundler/gems/rgeo-kml-e31a5c2bd56f/lib/rgeo/kml/interface.rb:88:in `decode'
        from (irb):11
        from /Users/daviddouglas/.rvm/gems/ruby-2.2.1/gems/railties-4.0.0/lib/rails/commands/console.rb:90:in `start'
        from /Users/daviddouglas/.rvm/gems/ruby-2.2.1/gems/railties-4.0.0/lib/rails/commands/console.rb:9:in `start'
        from /Users/daviddouglas/.rvm/gems/ruby-2.2.1/gems/railties-4.0.0/lib/rails/commands.rb:64:in `<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in `<main>'
```

**Comment by ldonnet** [comment]
I'm actually developing this part of the gem. I hope to release the kml decoding at the end of june.

**Comment by ldonnet** [comment]
Today I fix the decode method for geometry. Feature decoding is not included
